language: elixir
notifications:
  email: false
elixir:
  - 1.2.5
  - 1.3.0
  - 1.4.2
otp_release:
  - 18.0
  - 19.0
env:
  - MIX_ENV=test
script:
  - mix coveralls.travis
matrix:
  exclude:
    - elixir: 1.2.5
      otp_release: 19.0
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
